/*
GroupBy Retail

GroupBy Retail API

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gbretailapi

import (
	"encoding/json"
)

// checks if the RecommendationsErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecommendationsErrorResponse{}

// RecommendationsErrorResponse Error returned by the API.
type RecommendationsErrorResponse struct {
	// Identifier used for tracking purposes.
	TrackingId *string `json:"trackingId,omitempty"`
	// HTTP method of the API call which produced the error.
	Method *string `json:"method,omitempty"`
	// HTTP path of the API call which produced the error.
	Path *string `json:"path,omitempty"`
	// Error message.
	Message *string `json:"message,omitempty"`
}

// NewRecommendationsErrorResponse instantiates a new RecommendationsErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecommendationsErrorResponse() *RecommendationsErrorResponse {
	this := RecommendationsErrorResponse{}
	return &this
}

// NewRecommendationsErrorResponseWithDefaults instantiates a new RecommendationsErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecommendationsErrorResponseWithDefaults() *RecommendationsErrorResponse {
	this := RecommendationsErrorResponse{}
	return &this
}

// GetTrackingId returns the TrackingId field value if set, zero value otherwise.
func (o *RecommendationsErrorResponse) GetTrackingId() string {
	if o == nil || IsNil(o.TrackingId) {
		var ret string
		return ret
	}
	return *o.TrackingId
}

// GetTrackingIdOk returns a tuple with the TrackingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecommendationsErrorResponse) GetTrackingIdOk() (*string, bool) {
	if o == nil || IsNil(o.TrackingId) {
		return nil, false
	}
	return o.TrackingId, true
}

// HasTrackingId returns a boolean if a field has been set.
func (o *RecommendationsErrorResponse) HasTrackingId() bool {
	if o != nil && !IsNil(o.TrackingId) {
		return true
	}

	return false
}

// SetTrackingId gets a reference to the given string and assigns it to the TrackingId field.
func (o *RecommendationsErrorResponse) SetTrackingId(v string) {
	o.TrackingId = &v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *RecommendationsErrorResponse) GetMethod() string {
	if o == nil || IsNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecommendationsErrorResponse) GetMethodOk() (*string, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *RecommendationsErrorResponse) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *RecommendationsErrorResponse) SetMethod(v string) {
	o.Method = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *RecommendationsErrorResponse) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecommendationsErrorResponse) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *RecommendationsErrorResponse) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *RecommendationsErrorResponse) SetPath(v string) {
	o.Path = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *RecommendationsErrorResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecommendationsErrorResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *RecommendationsErrorResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *RecommendationsErrorResponse) SetMessage(v string) {
	o.Message = &v
}

func (o RecommendationsErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecommendationsErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TrackingId) {
		toSerialize["trackingId"] = o.TrackingId
	}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableRecommendationsErrorResponse struct {
	value *RecommendationsErrorResponse
	isSet bool
}

func (v NullableRecommendationsErrorResponse) Get() *RecommendationsErrorResponse {
	return v.value
}

func (v *NullableRecommendationsErrorResponse) Set(val *RecommendationsErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRecommendationsErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRecommendationsErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecommendationsErrorResponse(val *RecommendationsErrorResponse) *NullableRecommendationsErrorResponse {
	return &NullableRecommendationsErrorResponse{value: val, isSet: true}
}

func (v NullableRecommendationsErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecommendationsErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


