/*
GroupBy Retail

GroupBy Retail API

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gbretailapi

import (
	"encoding/json"
)

// checks if the ProductDtoColorInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductDtoColorInfo{}

// ProductDtoColorInfo struct for ProductDtoColorInfo
type ProductDtoColorInfo struct {
	// Product color families (array).
	ColorFamilies []string `json:"colorFamilies,omitempty"`
	// Product color (array).
	Colors []string `json:"colors,omitempty"`
}

// NewProductDtoColorInfo instantiates a new ProductDtoColorInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductDtoColorInfo() *ProductDtoColorInfo {
	this := ProductDtoColorInfo{}
	return &this
}

// NewProductDtoColorInfoWithDefaults instantiates a new ProductDtoColorInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductDtoColorInfoWithDefaults() *ProductDtoColorInfo {
	this := ProductDtoColorInfo{}
	return &this
}

// GetColorFamilies returns the ColorFamilies field value if set, zero value otherwise.
func (o *ProductDtoColorInfo) GetColorFamilies() []string {
	if o == nil || IsNil(o.ColorFamilies) {
		var ret []string
		return ret
	}
	return o.ColorFamilies
}

// GetColorFamiliesOk returns a tuple with the ColorFamilies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDtoColorInfo) GetColorFamiliesOk() ([]string, bool) {
	if o == nil || IsNil(o.ColorFamilies) {
		return nil, false
	}
	return o.ColorFamilies, true
}

// HasColorFamilies returns a boolean if a field has been set.
func (o *ProductDtoColorInfo) HasColorFamilies() bool {
	if o != nil && !IsNil(o.ColorFamilies) {
		return true
	}

	return false
}

// SetColorFamilies gets a reference to the given []string and assigns it to the ColorFamilies field.
func (o *ProductDtoColorInfo) SetColorFamilies(v []string) {
	o.ColorFamilies = v
}

// GetColors returns the Colors field value if set, zero value otherwise.
func (o *ProductDtoColorInfo) GetColors() []string {
	if o == nil || IsNil(o.Colors) {
		var ret []string
		return ret
	}
	return o.Colors
}

// GetColorsOk returns a tuple with the Colors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDtoColorInfo) GetColorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Colors) {
		return nil, false
	}
	return o.Colors, true
}

// HasColors returns a boolean if a field has been set.
func (o *ProductDtoColorInfo) HasColors() bool {
	if o != nil && !IsNil(o.Colors) {
		return true
	}

	return false
}

// SetColors gets a reference to the given []string and assigns it to the Colors field.
func (o *ProductDtoColorInfo) SetColors(v []string) {
	o.Colors = v
}

func (o ProductDtoColorInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductDtoColorInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ColorFamilies) {
		toSerialize["colorFamilies"] = o.ColorFamilies
	}
	if !IsNil(o.Colors) {
		toSerialize["colors"] = o.Colors
	}
	return toSerialize, nil
}

type NullableProductDtoColorInfo struct {
	value *ProductDtoColorInfo
	isSet bool
}

func (v NullableProductDtoColorInfo) Get() *ProductDtoColorInfo {
	return v.value
}

func (v *NullableProductDtoColorInfo) Set(val *ProductDtoColorInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableProductDtoColorInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableProductDtoColorInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductDtoColorInfo(val *ProductDtoColorInfo) *NullableProductDtoColorInfo {
	return &NullableProductDtoColorInfo{value: val, isSet: true}
}

func (v NullableProductDtoColorInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductDtoColorInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


