/*
GroupBy Retail

GroupBy Retail API

API version: 0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gbretailapi

import (
	"encoding/json"
)

// checks if the Sort type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Sort{}

// Sort struct for Sort
type Sort struct {
	// Field the order will be applied to.
	Field string `json:"field"`
	// OrderDto the products will appear in.
	Order interface{} `json:"order"`
}

// NewSort instantiates a new Sort object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSort(field string, order interface{}) *Sort {
	this := Sort{}
	this.Field = field
	this.Order = order
	return &this
}

// NewSortWithDefaults instantiates a new Sort object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSortWithDefaults() *Sort {
	this := Sort{}
	return &this
}

// GetField returns the Field field value
func (o *Sort) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *Sort) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *Sort) SetField(v string) {
	o.Field = v
}

// GetOrder returns the Order field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *Sort) GetOrder() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Order
}

// GetOrderOk returns a tuple with the Order field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Sort) GetOrderOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return &o.Order, true
}

// SetOrder sets field value
func (o *Sort) SetOrder(v interface{}) {
	o.Order = v
}

func (o Sort) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Sort) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["field"] = o.Field
	if o.Order != nil {
		toSerialize["order"] = o.Order
	}
	return toSerialize, nil
}

type NullableSort struct {
	value *Sort
	isSet bool
}

func (v NullableSort) Get() *Sort {
	return v.value
}

func (v *NullableSort) Set(val *Sort) {
	v.value = val
	v.isSet = true
}

func (v NullableSort) IsSet() bool {
	return v.isSet
}

func (v *NullableSort) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSort(val *Sort) *NullableSort {
	return &NullableSort{value: val, isSet: true}
}

func (v NullableSort) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSort) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


