/*
GroupBy Retail

GroupBy Retail API

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gbretailapi

import (
	"encoding/json"
)

// checks if the PriceInfoPriceEffectiveTime type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PriceInfoPriceEffectiveTime{}

// PriceInfoPriceEffectiveTime struct for PriceInfoPriceEffectiveTime
type PriceInfoPriceEffectiveTime struct {
	// Timestamp seconds.
	Seconds *int64 `json:"seconds,omitempty"`
	// Timestamp nanos.
	Nanos *int32 `json:"nanos,omitempty"`
}

// NewPriceInfoPriceEffectiveTime instantiates a new PriceInfoPriceEffectiveTime object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPriceInfoPriceEffectiveTime() *PriceInfoPriceEffectiveTime {
	this := PriceInfoPriceEffectiveTime{}
	return &this
}

// NewPriceInfoPriceEffectiveTimeWithDefaults instantiates a new PriceInfoPriceEffectiveTime object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPriceInfoPriceEffectiveTimeWithDefaults() *PriceInfoPriceEffectiveTime {
	this := PriceInfoPriceEffectiveTime{}
	return &this
}

// GetSeconds returns the Seconds field value if set, zero value otherwise.
func (o *PriceInfoPriceEffectiveTime) GetSeconds() int64 {
	if o == nil || IsNil(o.Seconds) {
		var ret int64
		return ret
	}
	return *o.Seconds
}

// GetSecondsOk returns a tuple with the Seconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PriceInfoPriceEffectiveTime) GetSecondsOk() (*int64, bool) {
	if o == nil || IsNil(o.Seconds) {
		return nil, false
	}
	return o.Seconds, true
}

// HasSeconds returns a boolean if a field has been set.
func (o *PriceInfoPriceEffectiveTime) HasSeconds() bool {
	if o != nil && !IsNil(o.Seconds) {
		return true
	}

	return false
}

// SetSeconds gets a reference to the given int64 and assigns it to the Seconds field.
func (o *PriceInfoPriceEffectiveTime) SetSeconds(v int64) {
	o.Seconds = &v
}

// GetNanos returns the Nanos field value if set, zero value otherwise.
func (o *PriceInfoPriceEffectiveTime) GetNanos() int32 {
	if o == nil || IsNil(o.Nanos) {
		var ret int32
		return ret
	}
	return *o.Nanos
}

// GetNanosOk returns a tuple with the Nanos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PriceInfoPriceEffectiveTime) GetNanosOk() (*int32, bool) {
	if o == nil || IsNil(o.Nanos) {
		return nil, false
	}
	return o.Nanos, true
}

// HasNanos returns a boolean if a field has been set.
func (o *PriceInfoPriceEffectiveTime) HasNanos() bool {
	if o != nil && !IsNil(o.Nanos) {
		return true
	}

	return false
}

// SetNanos gets a reference to the given int32 and assigns it to the Nanos field.
func (o *PriceInfoPriceEffectiveTime) SetNanos(v int32) {
	o.Nanos = &v
}

func (o PriceInfoPriceEffectiveTime) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PriceInfoPriceEffectiveTime) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Seconds) {
		toSerialize["seconds"] = o.Seconds
	}
	if !IsNil(o.Nanos) {
		toSerialize["nanos"] = o.Nanos
	}
	return toSerialize, nil
}

type NullablePriceInfoPriceEffectiveTime struct {
	value *PriceInfoPriceEffectiveTime
	isSet bool
}

func (v NullablePriceInfoPriceEffectiveTime) Get() *PriceInfoPriceEffectiveTime {
	return v.value
}

func (v *NullablePriceInfoPriceEffectiveTime) Set(val *PriceInfoPriceEffectiveTime) {
	v.value = val
	v.isSet = true
}

func (v NullablePriceInfoPriceEffectiveTime) IsSet() bool {
	return v.isSet
}

func (v *NullablePriceInfoPriceEffectiveTime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePriceInfoPriceEffectiveTime(val *PriceInfoPriceEffectiveTime) *NullablePriceInfoPriceEffectiveTime {
	return &NullablePriceInfoPriceEffectiveTime{value: val, isSet: true}
}

func (v NullablePriceInfoPriceEffectiveTime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePriceInfoPriceEffectiveTime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


