/*
GroupBy Retail

GroupBy Retail API

API version: 0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gbretailapi

import (
	"encoding/json"
)

// checks if the ErrorDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorDto{}

// ErrorDto Error returned by the API.
type ErrorDto struct {
	// Identifier used for tracking purposes.
	TrackingId *string `json:"trackingId,omitempty"`
	// HTTP method of the API call which produced the error.
	Method *string `json:"method,omitempty"`
	// HTTP path of the API call which produced the error.
	Path *string `json:"path,omitempty"`
	// Error message.
	Message *string `json:"message,omitempty"`
}

// NewErrorDto instantiates a new ErrorDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorDto() *ErrorDto {
	this := ErrorDto{}
	return &this
}

// NewErrorDtoWithDefaults instantiates a new ErrorDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorDtoWithDefaults() *ErrorDto {
	this := ErrorDto{}
	return &this
}

// GetTrackingId returns the TrackingId field value if set, zero value otherwise.
func (o *ErrorDto) GetTrackingId() string {
	if o == nil || IsNil(o.TrackingId) {
		var ret string
		return ret
	}
	return *o.TrackingId
}

// GetTrackingIdOk returns a tuple with the TrackingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorDto) GetTrackingIdOk() (*string, bool) {
	if o == nil || IsNil(o.TrackingId) {
		return nil, false
	}
	return o.TrackingId, true
}

// HasTrackingId returns a boolean if a field has been set.
func (o *ErrorDto) HasTrackingId() bool {
	if o != nil && !IsNil(o.TrackingId) {
		return true
	}

	return false
}

// SetTrackingId gets a reference to the given string and assigns it to the TrackingId field.
func (o *ErrorDto) SetTrackingId(v string) {
	o.TrackingId = &v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *ErrorDto) GetMethod() string {
	if o == nil || IsNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorDto) GetMethodOk() (*string, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *ErrorDto) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *ErrorDto) SetMethod(v string) {
	o.Method = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *ErrorDto) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorDto) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *ErrorDto) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *ErrorDto) SetPath(v string) {
	o.Path = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ErrorDto) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorDto) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ErrorDto) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ErrorDto) SetMessage(v string) {
	o.Message = &v
}

func (o ErrorDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TrackingId) {
		toSerialize["trackingId"] = o.TrackingId
	}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableErrorDto struct {
	value *ErrorDto
	isSet bool
}

func (v NullableErrorDto) Get() *ErrorDto {
	return v.value
}

func (v *NullableErrorDto) Set(val *ErrorDto) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorDto) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorDto(val *ErrorDto) *NullableErrorDto {
	return &NullableErrorDto{value: val, isSet: true}
}

func (v NullableErrorDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


