/*
GroupBy Retail

GroupBy Retail API

API version: 0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gbretailapi

import (
	"encoding/json"
)

// checks if the Overwrites type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Overwrites{}

// Overwrites struct for Overwrites
type Overwrites struct {
	Rules []RuleConfiguration `json:"rules"`
}

// NewOverwrites instantiates a new Overwrites object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOverwrites(rules []RuleConfiguration) *Overwrites {
	this := Overwrites{}
	this.Rules = rules
	return &this
}

// NewOverwritesWithDefaults instantiates a new Overwrites object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOverwritesWithDefaults() *Overwrites {
	this := Overwrites{}
	return &this
}

// GetRules returns the Rules field value
func (o *Overwrites) GetRules() []RuleConfiguration {
	if o == nil {
		var ret []RuleConfiguration
		return ret
	}

	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value
// and a boolean to check if the value has been set.
func (o *Overwrites) GetRulesOk() ([]RuleConfiguration, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rules, true
}

// SetRules sets field value
func (o *Overwrites) SetRules(v []RuleConfiguration) {
	o.Rules = v
}

func (o Overwrites) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Overwrites) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rules"] = o.Rules
	return toSerialize, nil
}

type NullableOverwrites struct {
	value *Overwrites
	isSet bool
}

func (v NullableOverwrites) Get() *Overwrites {
	return v.value
}

func (v *NullableOverwrites) Set(val *Overwrites) {
	v.value = val
	v.isSet = true
}

func (v NullableOverwrites) IsSet() bool {
	return v.isSet
}

func (v *NullableOverwrites) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOverwrites(val *Overwrites) *NullableOverwrites {
	return &NullableOverwrites{value: val, isSet: true}
}

func (v NullableOverwrites) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOverwrites) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


