/*
GroupBy Retail

GroupBy Retail API

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gbretailapi

import (
	"encoding/json"
)

// checks if the TemplateDtoTriggerSet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateDtoTriggerSet{}

// TemplateDtoTriggerSet struct for TemplateDtoTriggerSet
type TemplateDtoTriggerSet struct {
	// Query pattern triggers.
	QueryPatternTriggers []QueryPatternTrigger `json:"queryPatternTriggers"`
	// Selected refinement triggers.
	SelectedRefinementTriggers []SelectedRefinementTrigger `json:"selectedRefinementTriggers"`
	// Custom parameter triggers.
	CustomParameterTriggers []CustomParameterTrigger `json:"customParameterTriggers"`
}

// NewTemplateDtoTriggerSet instantiates a new TemplateDtoTriggerSet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateDtoTriggerSet(queryPatternTriggers []QueryPatternTrigger, selectedRefinementTriggers []SelectedRefinementTrigger, customParameterTriggers []CustomParameterTrigger) *TemplateDtoTriggerSet {
	this := TemplateDtoTriggerSet{}
	this.QueryPatternTriggers = queryPatternTriggers
	this.SelectedRefinementTriggers = selectedRefinementTriggers
	this.CustomParameterTriggers = customParameterTriggers
	return &this
}

// NewTemplateDtoTriggerSetWithDefaults instantiates a new TemplateDtoTriggerSet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateDtoTriggerSetWithDefaults() *TemplateDtoTriggerSet {
	this := TemplateDtoTriggerSet{}
	return &this
}

// GetQueryPatternTriggers returns the QueryPatternTriggers field value
func (o *TemplateDtoTriggerSet) GetQueryPatternTriggers() []QueryPatternTrigger {
	if o == nil {
		var ret []QueryPatternTrigger
		return ret
	}

	return o.QueryPatternTriggers
}

// GetQueryPatternTriggersOk returns a tuple with the QueryPatternTriggers field value
// and a boolean to check if the value has been set.
func (o *TemplateDtoTriggerSet) GetQueryPatternTriggersOk() ([]QueryPatternTrigger, bool) {
	if o == nil {
		return nil, false
	}
	return o.QueryPatternTriggers, true
}

// SetQueryPatternTriggers sets field value
func (o *TemplateDtoTriggerSet) SetQueryPatternTriggers(v []QueryPatternTrigger) {
	o.QueryPatternTriggers = v
}

// GetSelectedRefinementTriggers returns the SelectedRefinementTriggers field value
func (o *TemplateDtoTriggerSet) GetSelectedRefinementTriggers() []SelectedRefinementTrigger {
	if o == nil {
		var ret []SelectedRefinementTrigger
		return ret
	}

	return o.SelectedRefinementTriggers
}

// GetSelectedRefinementTriggersOk returns a tuple with the SelectedRefinementTriggers field value
// and a boolean to check if the value has been set.
func (o *TemplateDtoTriggerSet) GetSelectedRefinementTriggersOk() ([]SelectedRefinementTrigger, bool) {
	if o == nil {
		return nil, false
	}
	return o.SelectedRefinementTriggers, true
}

// SetSelectedRefinementTriggers sets field value
func (o *TemplateDtoTriggerSet) SetSelectedRefinementTriggers(v []SelectedRefinementTrigger) {
	o.SelectedRefinementTriggers = v
}

// GetCustomParameterTriggers returns the CustomParameterTriggers field value
func (o *TemplateDtoTriggerSet) GetCustomParameterTriggers() []CustomParameterTrigger {
	if o == nil {
		var ret []CustomParameterTrigger
		return ret
	}

	return o.CustomParameterTriggers
}

// GetCustomParameterTriggersOk returns a tuple with the CustomParameterTriggers field value
// and a boolean to check if the value has been set.
func (o *TemplateDtoTriggerSet) GetCustomParameterTriggersOk() ([]CustomParameterTrigger, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomParameterTriggers, true
}

// SetCustomParameterTriggers sets field value
func (o *TemplateDtoTriggerSet) SetCustomParameterTriggers(v []CustomParameterTrigger) {
	o.CustomParameterTriggers = v
}

func (o TemplateDtoTriggerSet) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateDtoTriggerSet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["queryPatternTriggers"] = o.QueryPatternTriggers
	toSerialize["selectedRefinementTriggers"] = o.SelectedRefinementTriggers
	toSerialize["customParameterTriggers"] = o.CustomParameterTriggers
	return toSerialize, nil
}

type NullableTemplateDtoTriggerSet struct {
	value *TemplateDtoTriggerSet
	isSet bool
}

func (v NullableTemplateDtoTriggerSet) Get() *TemplateDtoTriggerSet {
	return v.value
}

func (v *NullableTemplateDtoTriggerSet) Set(val *TemplateDtoTriggerSet) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateDtoTriggerSet) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateDtoTriggerSet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateDtoTriggerSet(val *TemplateDtoTriggerSet) *NullableTemplateDtoTriggerSet {
	return &NullableTemplateDtoTriggerSet{value: val, isSet: true}
}

func (v NullableTemplateDtoTriggerSet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateDtoTriggerSet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


