/*
GroupBy Retail

GroupBy Retail API

API version: 0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gbretailapi

import (
	"encoding/json"
)

// checks if the CustomParameterDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomParameterDto{}

// CustomParameterDto A key=value combination to allow for further triggering of rules or redirects.
type CustomParameterDto struct {
	// Key of the custom parameter.
	Key string `json:"key"`
	// Value of the custom parameter
	Value string `json:"value"`
}

// NewCustomParameterDto instantiates a new CustomParameterDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomParameterDto(key string, value string) *CustomParameterDto {
	this := CustomParameterDto{}
	this.Key = key
	this.Value = value
	return &this
}

// NewCustomParameterDtoWithDefaults instantiates a new CustomParameterDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomParameterDtoWithDefaults() *CustomParameterDto {
	this := CustomParameterDto{}
	return &this
}

// GetKey returns the Key field value
func (o *CustomParameterDto) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *CustomParameterDto) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *CustomParameterDto) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
func (o *CustomParameterDto) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *CustomParameterDto) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *CustomParameterDto) SetValue(v string) {
	o.Value = v
}

func (o CustomParameterDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomParameterDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

type NullableCustomParameterDto struct {
	value *CustomParameterDto
	isSet bool
}

func (v NullableCustomParameterDto) Get() *CustomParameterDto {
	return v.value
}

func (v *NullableCustomParameterDto) Set(val *CustomParameterDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomParameterDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomParameterDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomParameterDto(val *CustomParameterDto) *NullableCustomParameterDto {
	return &NullableCustomParameterDto{value: val, isSet: true}
}

func (v NullableCustomParameterDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomParameterDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


