/*
GroupBy Retail

GroupBy Retail API

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gbretailapi

import (
	"encoding/json"
)

// checks if the PriceInfoPriceExpireTime type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PriceInfoPriceExpireTime{}

// PriceInfoPriceExpireTime struct for PriceInfoPriceExpireTime
type PriceInfoPriceExpireTime struct {
	// Timestamp seconds.
	Seconds *int64 `json:"seconds,omitempty"`
	// Timestamp nanos.
	Nanos *int32 `json:"nanos,omitempty"`
}

// NewPriceInfoPriceExpireTime instantiates a new PriceInfoPriceExpireTime object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPriceInfoPriceExpireTime() *PriceInfoPriceExpireTime {
	this := PriceInfoPriceExpireTime{}
	return &this
}

// NewPriceInfoPriceExpireTimeWithDefaults instantiates a new PriceInfoPriceExpireTime object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPriceInfoPriceExpireTimeWithDefaults() *PriceInfoPriceExpireTime {
	this := PriceInfoPriceExpireTime{}
	return &this
}

// GetSeconds returns the Seconds field value if set, zero value otherwise.
func (o *PriceInfoPriceExpireTime) GetSeconds() int64 {
	if o == nil || IsNil(o.Seconds) {
		var ret int64
		return ret
	}
	return *o.Seconds
}

// GetSecondsOk returns a tuple with the Seconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PriceInfoPriceExpireTime) GetSecondsOk() (*int64, bool) {
	if o == nil || IsNil(o.Seconds) {
		return nil, false
	}
	return o.Seconds, true
}

// HasSeconds returns a boolean if a field has been set.
func (o *PriceInfoPriceExpireTime) HasSeconds() bool {
	if o != nil && !IsNil(o.Seconds) {
		return true
	}

	return false
}

// SetSeconds gets a reference to the given int64 and assigns it to the Seconds field.
func (o *PriceInfoPriceExpireTime) SetSeconds(v int64) {
	o.Seconds = &v
}

// GetNanos returns the Nanos field value if set, zero value otherwise.
func (o *PriceInfoPriceExpireTime) GetNanos() int32 {
	if o == nil || IsNil(o.Nanos) {
		var ret int32
		return ret
	}
	return *o.Nanos
}

// GetNanosOk returns a tuple with the Nanos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PriceInfoPriceExpireTime) GetNanosOk() (*int32, bool) {
	if o == nil || IsNil(o.Nanos) {
		return nil, false
	}
	return o.Nanos, true
}

// HasNanos returns a boolean if a field has been set.
func (o *PriceInfoPriceExpireTime) HasNanos() bool {
	if o != nil && !IsNil(o.Nanos) {
		return true
	}

	return false
}

// SetNanos gets a reference to the given int32 and assigns it to the Nanos field.
func (o *PriceInfoPriceExpireTime) SetNanos(v int32) {
	o.Nanos = &v
}

func (o PriceInfoPriceExpireTime) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PriceInfoPriceExpireTime) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Seconds) {
		toSerialize["seconds"] = o.Seconds
	}
	if !IsNil(o.Nanos) {
		toSerialize["nanos"] = o.Nanos
	}
	return toSerialize, nil
}

type NullablePriceInfoPriceExpireTime struct {
	value *PriceInfoPriceExpireTime
	isSet bool
}

func (v NullablePriceInfoPriceExpireTime) Get() *PriceInfoPriceExpireTime {
	return v.value
}

func (v *NullablePriceInfoPriceExpireTime) Set(val *PriceInfoPriceExpireTime) {
	v.value = val
	v.isSet = true
}

func (v NullablePriceInfoPriceExpireTime) IsSet() bool {
	return v.isSet
}

func (v *NullablePriceInfoPriceExpireTime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePriceInfoPriceExpireTime(val *PriceInfoPriceExpireTime) *NullablePriceInfoPriceExpireTime {
	return &NullablePriceInfoPriceExpireTime{value: val, isSet: true}
}

func (v NullablePriceInfoPriceExpireTime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePriceInfoPriceExpireTime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


